# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $queryBus: '@tactician.commandbus.query'
            $commandBus: '@tactician.commandbus.command'

    App\:
        resource: '../src/'
        exclude: '../src/{Application}'

    App\Application\Command\:
        resource: '../src/Application/Command'
        exclude: '../src/Application/Command/**/*Command.php'
        tags:
            - { name: tactician.handler, typehints: true, bus: command }

    App\Application\Query\:
        resource: '../src/Application/Query'
        exclude: '../src/Application/Query/**/*Query.php'
        tags:
            - { name: tactician.handler, typehints: true, bus: query }

    App\UI\Http\Rest\:
        resource: '../src/UI/Http/Rest/'

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller'
        tags: ['controller.service_arguments']

    App\UI\Http\Web\Controller\:
        resource: '../src/UI/Http/Web/Controller'
        tags: ['controller.service_arguments']